### ISSUE TITLE
assign: dimensions of a and b do not match.

### ISSUE THREAD

**Issue by yuang-chen** [GraphBLAS/rgri#4]
Hello, 

I noticed a weird failure when playing around the `grb::assign`  function.

the `grb::shape(a) == grb::shape(b)` inside `grb::assign` function fails to work, though it outputs correct results when used outside of the function. My code is:

 ```cpp
#include <grb/grb.hpp>

int main(int argc, char** argv) {
  
  grb::matrix<float> a({10, 10});

  a[{2, 3}] = 12;
  a[{7, 1}] = 12;
  a[{5, 5}] = 12;
  a[{2, 7}] = 12;
  a[{9, 6}] = 12;

  grb::matrix<float> b({10, 10});

  b[{3, 3}] = 3;
  b[{4, 4}] = 4;
  b[{5, 5}] = 5;

  if(grb::shape(a) == grb::shape(b)) 
  {
    std::cout << "a and b are equal size" << std::endl;
  }
  grb::assign(a, b);

  return 0;
}

```
and the output of terminal is:
```sh
a and b are equal size
terminate called after throwing an instance of 'grb::invalid_argument'
  what():  assign: dimensions of a and b do not match.
```

Testing Env (with multiple g++):
```sh
Ubuntu 20.04.4 LTS
Kernel 5.4.0-125-generic
g++12.2.0, 11.3.0, 10.3.0
```
The error disappears if I set compiler optimization level to 0, e.g., `CXXFLAGS = -std=c++20 -O0 -I$(GRB_DIR)`. However, the error appears again when optimization level is 1 or 2. 

Can you please let me know the compiler used for implementing RGRI? I would like to try for testing. I am new to c++20, and have spent hours in debugging but still have no clue.

**Comment by BenBrock** [comment]
I'm not able to reproduce this issue, but I suspect it may have to do with my implementation of `grb::get`.  I'll take another look at this this afternoon.

**Comment by BenBrock** [comment]
I was able to reproduce the issue on an x86-64 system.  I just added [a fix to replace a missing return statement](https://github.com/GraphBLAS/rgri/commit/eec1283526d5eaa902d2ecc5f01f104daec7ad3f), which I believe is what was causing the issue.

Let me know if this fixes it for you.

(For some background, in GCC 9, they added some changes to the optimizers that caused missing return statements to result in catastrophic failures with optimizations turned on.  Before this, the code would often run as intended.  I had mostly been testing on an arm64 system, so my guess is that the ARM optimizers still let more of these missing return statement bugs pass silently.  It could possibly also be a compiler distribution issue, but if I had to guess I'd say it was architecture-specific optimizations causing the issue.)

**Comment by yuang-chen** [comment]
The added return statement fixed the error. Thanks for your explanation. 

I indeed noticed that the compiler's warning message about the missing return statement when I was debugging the code. Nonetheless, I was totally unaware of its potential side impact on the program as you mentioned, so I just left it as it is.  A valuable lesson is learnt.

Thanks again for the clarification. :)
